### ISSUE TITLE
Getting error "'SSL certificate problem: unable to get local issuer certificate'"

### ISSUE THREAD

**Issue by d3athrow** [milo/github-api#32]
```
Fatal error: Uncaught exception 'Milo\Github\Http\BadResponseException' with message 'SSL certificate problem: unable to get local issuer certificate' in C:\xampp\htdocs\issues-classes\vendor\milo\github-api\src\Github\Http\CurlClient.php:108 Stack trace: #0 C:\xampp\htdocs\issues-classes\vendor\milo\github-api\src\Github\Http\AbstractClient.php(49): Milo\Github\Http\CurlClient->process(Object(Milo\Github\Http\Request)) #1 C:\xampp\htdocs\issues-classes\vendor\milo\github-api\src\Github\Api.php(202): Milo\Github\Http\AbstractClient->request(Object(Milo\Github\Http\Request)) #2 C:\xampp\htdocs\issues-classes\vendor\milo\github-api\src\Github\Api.php(106): Milo\Github\Api->request(Object(Milo\Github\Http\Request)) #3 C:\xampp\htdocs\baka\issues\index.php(186): Milo\Github\Api->get('/search/issues?...') #4 C:\xampp\htdocs\baka\issues\index.php(132): check_for_unique('pomftest') #5 {main} thrown in C:\xampp\htdocs\issues-classes\vendor\milo\github-api\src\Github\Http\CurlClient.php on line 108
```
Full error above. I've used this api for several years without problems and now i'm getting this error on submitting an api request. Any idea why or how to fix it?

**Comment by milo** [comment]
Hi,
looks like GitHub changed certification authority chain of API endpoints certificate. You can adjust that via [SSL settings of clients](https://github.com/milo/github-api/wiki/HTTP-clients) or just update to the version 1.4.8 I just released. I updated bundled CA chain.

**Comment by d3athrow** [comment]
thanks, that fixed it.
